"""Add num_comments field to Post model

Revision ID: 5257e9e7845f
Revises: 4000dab9ff18
Create Date: 2023-07-06 22:33:01.972311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5257e9e7845f'
down_revision = '4000dab9ff18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('_password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password_hash', sa.VARCHAR(), nullable=False))

    # ### end Alembic commands ###
